spring:
  profiles:
    active: "peer-1"


---


spring:
  profiles: peer-1
  application:    name: eureka-server-clustered
eureka:
  instance:
    hostname: eureka-peer1
    appname: eureka-server-clustered
  client:
    serviceUrl:
      defaultZone: http://eureka-peer2:7770/eureka/
    register-with-eureka: true
    fetch-registry: true
server:
  port: 7765
  
---  

spring:
  profiles: peer-2
  application:
    name: eureka-server-clustered
eureka:
  instance:
      hostname: eureka-peer2
      appname: eureka-server-clustered
  client:
    serviceUrl:
      defaultZone: http://eureka-peer1:7765/eureka/
    register-with-eureka: true
    fetch-registry: true
server:
  port: 7770
