spring:
  profiles: default
eureka:
  instance:
  
    hostname: default-eureka-server.com
    appname: eureka-cluster
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
server:
  port: 8761

---
spring:
  profiles: peer-1
  application:    name: eureka-server-clustered
eureka:
  instance:
  
    hostname: eureka-peer1
    appname: eureka-server-clustered
  client:
    serviceUrl:
      defaultZone: http://eureka-peer2:8770/eureka/
      register-with-eureka: true
    fetch-registry: true
server:
  port: 8765
  
---  

spring:
  profiles: peer-2
  application:
    name: eureka-server-clustered
eureka:
  instance:
  
    hostname: eureka-peer2
    appname: eureka-server-clustered
  client:
    serviceUrl:
      defaultZone: http://eureka-peer1:8765/eureka/
      register-with-eureka: true
    fetch-registry: true
server:
  port: 8770
