spring:
  application:
    name: cluster-client

server:
  port: 6060
eureka:
  client:
    service-url:
      defaultZone: http://eureka-peer1:8765/eureka,http://eureka-peer2:8770/eureka
 
    
  instance:
    appname: cluster-client
      
